version: '3.6'
services:
  pix2code:
    privileged: true
    container_name: pix2code
    image: pix2code-image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /path-to-repo/pix2code/dreamcoder:/workspace/
    entrypoint: bash
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '6' ]
              capabilities: [ gpu ]
